# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for hammerhead configurations
Name: jolla-configuration-hammerhead
Requires:
- pattern:jolla-hw-adaptation-hammerhead
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland
# For devices with cellular modem. Those without one, please comment out:
- pattern:jolla-sailfish-cellular-apps
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

- sailfish-content-graphics-z@ICON_RES@

# For multi-SIM devices
#- jolla-settings-networking-multisim

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

# Jolla Store 
- store-client
- jolla-settings-accounts-extensions-jolla

#Missing packages in 2.1.1.24
- jolla-settings-accounts-extensions-jabber
- jolla-settings-system-sideloading

# For Mozilla location services (online)
- geoclue-provider-mlsdb

# Sailfish OS CSD tool for hardware testing
# needs some configuration to get all features working
- csd

Summary: Jolla Configuration hammerhead

